src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Otus.Teaching.Pcf.GivingToCustomer.WebHost.Models;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Controllers
{
   public class CustomersController : Controller
   {
      private readonly Api.CustomersController _customersController;
      private readonly Api.PreferencesController _preferencesController;

      public CustomersController(Api.CustomersController customersController,
         Api.PreferencesController preferencesController)
      {
         _customersController = customersController;
         _preferencesController = preferencesController;
      }

      public async Task<IActionResult> Index()
      {
         var result = await _customersController.GetCustomersAsync();
         var customers = ((OkObjectResult)result.Result).Value;

         return View("Index", customers);
      }
      
      [HttpPost]
      public async Task<IActionResult> Create(CreateOrEditCustomerRequest customer)
      {
         if (ModelState.IsValid)
         {
            await _customersController.CreateCustomerAsync(customer);
         }

         return Redirect(nameof(Index));
      }

      public async Task<IActionResult> Edit(Guid id)
      {
         var customerResult = await _customersController.GetCustomerAsync(id);
         var customer = (CustomerResponse)((OkObjectResult)customerResult.Result).Value;

         var allPreferencesResult = await _preferencesController.GetPreferencesAsync();
         var allPreferences = (List<PreferenceResponse>)((OkObjectResult)allPreferencesResult.Result).Value;

         customer.AllPreferences = new MultiSelectList(allPreferences, "Id", "Name");
         customer.SelectedPreferences = customer.Preferences.Select(x => x.Id).ToList();

         return View(customer);
      }

      [HttpPost]
      public async Task<IActionResult> Edit(Guid id, CustomerResponse customer)
      {
         if (ModelState.IsValid)
         {
            var editRequest = new CreateOrEditCustomerRequest
            {
               FirstName = customer.FirstName,
               LastName = customer.LastName,
               Email = customer.Email,
               PreferenceIds = customer.SelectedPreferences
            };

            await _customersController.EditCustomersAsync(id, editRequest);
            return RedirectToAction(nameof(Index));
         }

         return await Edit(id);
      }
      
      public async Task<IActionResult> Delete(Guid id)
      {
         var result = await _customersController.GetCustomerAsync(id);
         var customer = ((OkObjectResult)result.Result).Value;

         return View(customer);
      }

      [HttpPost, ActionName("Delete")]
      public async Task<IActionResult> DeleteCustomer(Guid id)
      {
         await _customersController.DeleteCustomerAsync(id);
         return RedirectToAction(nameof(Index));
      }
   }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Controllers/PreferencesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Controllers
{
   public class PreferencesController : Controller
   {
      private readonly Api.PreferencesController _preferencesController;

      public PreferencesController(Api.PreferencesController preferencesController)
      {
         _preferencesController = preferencesController;
      }

      public async Task<IActionResult> Index()
      {
         var result = await _preferencesController.GetPreferencesAsync();
         var preferences = ((OkObjectResult)result.Result).Value;

         return View("Index", preferences);
      }
   }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Controllers/PromocodesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Otus.Teaching.Pcf.GivingToCustomer.WebHost.Controllers
{
   public class PromocodesController : Controller
   {
      private readonly Api.PromocodesController _promocodesController;

      public PromocodesController(Api.PromocodesController promocodesController)
      {
         _promocodesController = promocodesController;
      }

      public async Task<IActionResult> Index()
      {
         var result = await _promocodesController.GetPromocodesAsync();
         var promocodes = ((OkObjectResult)result.Result).Value;

         return View("Index", promocodes);
      }
   }
}

src/Otus.Teaching.Pcf.GivingToCustomer/Otus.Teaching.Pcf.GivingToCustomer.WebHost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RazorApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-multiselect.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customers" asp-action="Index">Customers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Promocodes" asp-action="Index">Promocodes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Preferences" asp-action="Index">Preferences</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - RazorApp
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap-multiselect.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>